### ISSUE TITLE
书名建议

### ISSUE THREAD

**Issue by githubsoftware2015** [hollischuang/toBeTopJavaer#167]
Java工程师成神指南

**Comment by Mike-7777777** [comment]
能再无聊点？

傳送自 Yahoo奇摩電子信箱 Android 版 
 
   在 2021 年 11月 月 22 日週一，時間：上午 11:39 ， githubsoftware2015 ***@***.***> 寫道：   


Java工程师成神指南

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by githubsoftware2015** [comment]
名字不重要，重要的是干货
